name: Testrun
on:
  push:
    branches:
      - "release"

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout to release
#        uses: actions/checkout@v3

#      - name: Docker Login
#       uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
#      - name: Build and push
#        uses: docker/build-push-action@v2
#        with:
#          push: true
#          tags: emmanuelsoon/randnum:ref
      
      - name: Sending message to slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Name: \n Matric number: \n "
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

